server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD_DB:2003}
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  message:
    basename: i18n/message
    encoding: UTF-8
    default-locale: en
jwt:
  expiration: 86400
  #30 days = 30 * 24 * 60 * 60
  secretKey: ${JWT_SECRET:NL1x/M2kLalft5G+P8qyfY+oLLl9sJx+k1/ZTbw9gD4=}
