server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://103.126.161.148:5432/task_management
    username: postgres
    password: "2003"   
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  message:
    basename: i18n/message
    encoding: UTF-8
    default-locale: en

jwt:
  expiration: 86400
  secretKey: NL1x/M2kLalft5G+P8qyfY+oLLl9sJx+k1/ZTbw9gD4=
